### ISSUE TITLE
Theme submission issues

### ISSUE THREAD

**Issue by digitalcraftsman** [themefisher/restaurant-hugo-theme#1]
Hello @themefisher team,

since the discussion in https://github.com/gohugoio/hugoThemes/issues/381 mixes up quite a lot of topics I moved the comment about my review of this theme to this issue. Please fix the issues mentioned above in order to add this theme to www.gohugo.io

---

While checking the repository of the restaurant theme I noticed that the metadata in [theme.toml](https://github.com/themefisher/restaurant-hugo-theme/blob/master/theme.toml) and the screenshots in `images` are missing.

Furthermore, the `LICENSE` file contains (by default) the MIT license while the README states, that the theme is released under the Creative Commons license. I guess you want to use the latter one. Hence please update the license text accordingly.

Could you add a rule to `.gitingore` that prevents the tracking of .DS_STORE` files and remove the existing ones?

Please let me know when you fixed the issues.

**Comment by mehedi-sharif** [comment]
We fixed this issue . Could you please check https://github.com/themefisher/restaurant-hugo . We fixed this issues . 
Thanks

**Comment by digitalcraftsman** [comment]
Thank you for fixing the issues. Your theme has been added in https://github.com/gohugoio/hugoThemes/commit/7c5514ed6dda60b64ebbd39d3ca47241dcc2ecbd and was already mentioned on Hugo official Twitter account.
